services:
  postgres:
    image: postgres:15
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: task_manager_redis
    ports:
      - "6379:6379"

  identity-service:
    build:
      context: ./identity-service
    container_name: identity_service
    expose:
      - "3000"
    environment:
      ACCESS_TOKEN_SECRET: secretaccess
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: task_manager
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  notes-service:
    build:
      context: ./notes-service
    container_name: notes_service
    expose:
      - "3000"
    environment:
      ACCESS_TOKEN_SECRET: secretaccess
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: task_manager
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    depends_on:
      - identity-service
      - notes-service